name: Code Review

on:
  pull_request:  # 对任何分支的 PR 都会触发工作流

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Code Review Comment
        run: echo "Code review passed"